### ISSUE TITLE
<Group capstone: set up your Kanban board>

### ISSUE THREAD

**Issue by Bestbynature** [Bestbynature/CineScope#79]
## This is a GitHub issue created in order for our group repo to be reviewed. below are the required details:

- [ ] ⚡ Link to the GItHub project: https://github.com/Bestbynature/CineScope/projects/3

- [ ] ⚡ Number of teammates: 2 (two). ✔️

**Comment by rloterh** [comment]
Hi Team, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on but you are almost there!
 🚦   __🏃  🏡 🏃‍♂️  🏚️ 🌴 🗼 

## Highlights 👍  
🎲 Created correct number of cards as per the group!

## Required Changes ♻️
- [ ] Cards are not assigned to any member of the group yet. Let's ensure that **all** cards are assigned to a team members accordingly.

**Tasks not assigned:**
![image](https://user-images.githubusercontent.com/12745474/232488808-85468a44-ab3f-46d9-aca8-e7469fdf9439.png)

![image](https://user-images.githubusercontent.com/12745474/232489054-665afc4e-e3e7-4bb7-93d5-482868eaf01c.png)

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by OyePriscilla** [comment]
Hi @rloterh and @Bestbynature 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Added link to GitHub project ✔️
Listed the number of people in the group ✔️
Assigned the group task to member of the group fairly ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
